plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kizari.dailynotify'
    compileSdk 36

    defaultConfig {
        applicationId 'com.kizari.dailynotify'
        minSdk 23
        targetSdk 36
        versionCode 2
        versionName '1.1'
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.10.1'
}
