plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kizari.dailynotify'
    compileSdk 36

    defaultConfig {
        applicationId 'com.kizari.dailynotify'
        minSdk 23
        targetSdk 36
        versionCode 3
        versionName '1.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.12.0'
}
